const febHolidays = [
    "My dear girl, please feel it",
    "This is the cycle of love feel it good 😏❤️",
    "You are my friend,my love,my everything 😊",
    "And will be always ❤",
    "I love you❤️",
    "You're my everything ",
    "You are my soulmate ✨💕",
    "You are my princess 💕 ",
    "And of course... wait darling.....",
    "My cutest wife🤭",
    "I will always be there for you",
    "No matter how far we are🥰",
    "I promise I will never do anything wrong/bad with you🥺❤️",
    "You're the prettiest, cutest, funniest,",
    "sweetest girl I have ever seen",
    "In one word, you're just perfect 🫠",
    "I'm the happiest boy to have you🥰",
    "I'm so grateful I met you❤️",
    "I'll always do my best to keep you happy my love 🥺",
];
